services:
  mysql:
    image: mysql:8.4
    container_name: saven-infraops-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: saven_infraops
      MYSQL_USER: infraops
      MYSQL_PASSWORD: infraops123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql


  redis:
    image: redis:7-alpine
    container_name: saven-infraops-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  mailhog:
    image: mailhog/mailhog:latest
    container_name: saven-infraops-mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  mysql_data:
